### ISSUE TITLE
Cobweb and spider cobweb have the same craft

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#182]
All 2 item have the same craft : 5 coton

**Comment by Ombridride** [comment]
I understand, we have earlier tweaked the two crafts for avoid that, i need to checks the mods

**Comment by LeMagnesium** [comment]
The two nodes appear to have different behaviors. Homedecor's cobwebs are able to change they rendering depending on the nodes around them, to give the illusion they stick to other nodes. Mobs' cobwebs are less aesthetic, which is why I granted them a less complicated craft recipe with only 4 strings needed.
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/be6cd218ce4a71b908b7e719b1138bc80683eafa

**Comment by Ombridride** [comment]
Thank you @Mg for :

1) Stole me this issue without ask me something,
2) Tweak a recipe wich don't NEED to be tweaked,
3) Force me to revert you useless code,
4) Revert the commented changes in your homedecor updates
5) Give me more work.......

https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/458b6fe64a1870cfd5a3368b22bb4d09215d85a6
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/30b65de3848af3e1ebc594cdf3a688b31206ab07

Now fixed.
