### ISSUE TITLE
The steel texture and the silver texture look the same

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#193]
on these screenshot i placed one bloc and one ingot of eah and i cant see any difference without texture pack.

with texture pack :
![sans titre2](https://cloud.githubusercontent.com/assets/11613522/9136975/ec02ebc8-3d1a-11e5-9baa-ae2874c56df8.png)

Without texture pack :
![sans titre](https://cloud.githubusercontent.com/assets/11613522/9136918/7580655c-3d1a-11e5-86f3-4a129d43716f.png)

**Comment by ObaniGemini** [comment]
+1

**Comment by Ombridride** [comment]
It's due to the merge of the Minetest_Game, someone had done a mistake... 

Indeed, we have changed the steel texture for being more black since a long lime...

Need to solve it... (and rollback again new changes...)

Thank you for the report

**Comment by LeMagnesium** [comment]
First, texture packs don't matter.

> Yay, someone done again a mistake... :(

Second, well it seems I can't do anything right these times. Though, using `default_steel_block.png` as an example, here are all our commits that affected this file since the creation of the repository :
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/bd37f19662202d596eca5fb35d0e9177b8a6e8db
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/b0871dfe0fccb604d2c887551d7469b695842faf
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/b8a1cac0cbc2dc2ced722f021fdb02ad7df7de5d
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/14b93fe4fbfaead61ca3a140bb3c7da76485a06d
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/fe926d914ba8313e40c8c4ac0170fc16e2ab9643
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/232b274c557b42da2393245dae308b623aaf63fe

The texture @farfadet46 has for steel blocks is the exact one which was inserted in our repository with the first commit, and whenever I did wrong, you fixed it. https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/14b93fe4fbfaead61ca3a140bb3c7da76485a06d is a neat example of that. These are **our** texture, so, whatever is the reason for that problem, it's not that our texture has changed.

**Comment by Ombridride** [comment]
Great investigation, but we don't need the commits (with all other useless things), we just need "blame" files if we need to compared properly the textures :)

So, if your investigation is right, and if you're sure, you can tweak the textures to be more different (darker for steel/lighter for silver)

**Comment by LeMagnesium** [comment]
> we just need "blame" files

Try to git blame a binary file. It's useless. Blame works line per line, and a binary file is not a standard text file. I linked commits so that you could check the previews of `default_steel_block.png` and `default_steel_block.png`.
I will modificate the texture as requested.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/35e4b996e74ee5e3b847e75fd02517e650649047
I increased the contrast and decreased luminosity.

**Comment by Ombridride** [comment]
Great job @LeMagnesium !

Need to do this in our HG server now (no silver, but it still a good idea to accustom players to the new color of the steel)

I opened an issue here https://github.com/MinetestForFun/hungry_games/issues/25
