### ISSUE TITLE
Some problem with light on stairs

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#198]
maybe a problem in the core ?
![sans titre](https://cloud.githubusercontent.com/assets/11613522/9154827/52c57730-3ea2-11e5-8ec0-ee6146d04335.png)

**Comment by gravgun** [comment]
Might be related to the stairs model, since it doesn't have face normals light computation might be wrong.
(Side node: Winblows 10, eww. Enjoy your NSA OS.)

**Comment by farfadet46** [comment]
yep for NSA :(

**Comment by Ombridride** [comment]
This bug is knowed like a very long time, and im my memories, we can't fix this because it's a core shaders bug

Indeed, the light parameters is handled in a strange way for all stairs/slabs and that's the point... This problem is already reported in the core dev team :)

So, it's a core bug and we can't do anything (server side).

I closed the issue. Anyway, thank you for your report !
