### ISSUE TITLE
Update [throwing] mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#206]
https://forum.minetest.net/viewtopic.php?f=11&t=11437&start=50#p185978

Be carful of our many tweakssss !!!

The new (mese)CrossBow is for the Hunter class.

**Comment by LeMagnesium** [comment]
That's not really a mese crossbow, just a automated arbalest.
Fortunately, I had nothing to change in our code, just add the needed lines. I just need to write that if at any moment we need to modificate the arrows' behavior from throwing's source (in the `arrow_*.lua` files) it would be a terrible mess because of what we have already tweaked.

https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/aa2f62afb343410e8146c866562620f00fd9d364

**Comment by Ombridride** [comment]
It's an automated crossbow with mesecons system to do it :) (story line in the forum topic)
