### ISSUE TITLE
The filter injector works only on the left side of double chest

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#209]
![screenshot_20150811_154427](https://cloud.githubusercontent.com/assets/11613522/9198994/1a9c0582-4040-11e5-8c9f-bea6030349ed.png)

this one don't works :
![screenshot_20150811_155054](https://cloud.githubusercontent.com/assets/11613522/9199127/f5fb9a48-4040-11e5-91d8-43db99ed1c5a.png)

**Comment by farfadet46** [comment]
i think the problem is from here :
![screenshot_20150811_155502](https://cloud.githubusercontent.com/assets/11613522/9199220/89948210-4041-11e5-9980-211211ba41c5.png)
 only the left side of the chest is a node / breakable ?

**Comment by Ombridride** [comment]
Err... As I readed from a VanessaE topic (a long time ago); so i think the minetest core doesn't permit to place/active a 2x1 node at the same time, or something like that... (This is why when you place sofas/beds/etc, you place one node, wich print a seconc "inactive" node)

So i think it's not possible... But i wait a seocnd opinion because it's a little to complicated for me :p

**Comment by LeMagnesium** [comment]
I will be clear. This double chest is a single node. It's visual rendering just take the room of two nodes. To check : try to dig the right side. The crack animation will appear on the left side (which is the real position of the node).
Unless we modify every wielder from pipeworks, it's impossible to fix this, and even if we did, it would be a mess, because it would add compatibility for a trick by a mod.

**Comment by Ombridride** [comment]
Ok, so i closed this issue, no need to tweak anything, it works like that only for a side and it's good like this.
