### ISSUE TITLE
Areas not working

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#234]
3 days ago I was able to put torches in @Gael-de-Sailly 's home. I was thinking itt was due to some mistake in my perms.
Now someone broke the factory I've spend hours on. I put a screenshot.  Please note we are in a protected area, and that a node breaker [EDIT: SORRY; I FOUND IT BACK]: and tons of sand nodes have been digged. It was supposed to be full of sand... and of course the lava was in a hole, and is not supposed to flow anywhere.

![capture du 2015-08-22 22 32 02](https://cloud.githubusercontent.com/assets/12512762/9425787/f41f7f28-491e-11e5-9339-3327a6c25895.png)

It's really annoying, area must protect our buildings! Or it's useless.

**Comment by Gael-de-Sailly** [comment]
xD I've noticed the 6 torches on my house and really asked myself about it !

**Comment by Cyberpangolin** [comment]
my apologizes for the inconvenience. The good thing is now you have light in your house :)

**Comment by Ombridride** [comment]
Wasn't a grief !

The sand was faling because of a node digged/refresh, and becase of the sand's falling property, the ground was falling with it...

For the torches in the @Gael-de-Sailly 's house, i've noticed you has the "area admin" privilege, certainly due to the spawn building, now you don't have this privilege anymore :)

Everything is Done, Closed the issue.

**Comment by Gael-de-Sailly** [comment]
Thank you for the torches xD
