### ISSUE TITLE
leafs de-pop too fast

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#242]
break a tree
all leaves get immediately de-popped
-> the delay and the chances of de-pop should be tweaked.
You sometimes lose all the leaves.

**Comment by LeMagnesium** [comment]
With that you won't lose any leave and the items will be dropped as they were :
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/2df673dc17968a6c494821926cdced09fbb84be0

The code from moretrees overriding the leafdecay mechanism was removed and now it's default's code which is executed, dropping nothing, but saplings, sometimes. I fixed that, yet you even get leaves when you dropped saplings, I think something buggy has happened and leaves cannot drop themselves anymore (because they should).
